<?php
$notas=array(
"Luis"=>array("Biologia"=>7,"Latin"=>5,"Fisica"=>5),
"Julia"=>array("Biologia"=>6,"Latin"=>6,"Fisica"=>5,"Tecnologia"=>8),
"Marta"=>array("Biologia"=>8,"Latin"=>6,"Fisica"=>6),
"Andres"=>array("Biologia"=>4,"Latin"=>4,"Fisica"=>3),
"Pedro"=>array("Biologia"=>5,"Latin"=>5,"Fisica"=>2)
);
?>