
<?php 
$trayectos=array(
array("origen"=>"SANTA JUSTA",
"destino"=>"FRANCIA",
"tren"=>"TALGO",
"salida"=>"09:00",
"llegada"=>"21:00"),

array("origen"=>"SANTA JUSTA",
"destino"=>"ATOCHA",
"tren"=>"AVE",
"salida"=>"06:00",
"llegada"=>"08:20"),
array("origen"=>"SANTA JUSTA",
"destino"=>"ATOCHA",
"tren"=>"AVE",
"salida"=>"18:20",
"llegada"=>"20:30"),
array("origen"=>"FRANCIA",
"destino"=>"SANTA JUSTA",
"tren"=>"TALGO",
"salida"=>"21:00",
"llegada"=>"07:00"),
array("origen"=>"SANTA JUSTA",
"destino"=>"ATOCHA",
"tren"=>"AVE",
"salida"=>"20:10",
"llegada"=>"22:40"),
array("origen"=>"SANTA JUSTA",
"destino"=>"ATOCHA",
"tren"=>"AVE",
"salida"=>"22:30",
"llegada"=>"0:50"),
array("origen"=>"ATOCHA",
"destino"=>"SANTA JUSTA",
"tren"=>"AVE",
"salida"=>"08:30",
"llegada"=>"10:50"),
array("origen"=>"ATOCHA",
"destino"=>"SANTA JUSTA",
"tren"=>"AVE",
"salida"=>"17:00",
"llegada"=>"19:30"),
array("origen"=>"ATOCHA",
"destino"=>"SANTA JUSTA",
"tren"=>"AVE",
"salida"=>"10:00",
"llegada"=>"12:30"),
array("origen"=>"ATOCHA",
"destino"=>"CORDOBA",
"tren"=>"AVE",
"salida"=>"16:00",
"llegada"=>"17:40"),
array("origen"=>"ATOCHA",
"destino"=>"FRANCIA",
"tren"=>"AVE",
"salida"=>"07:00",
"llegada"=>"09:50"),
array("origen"=>"ATOCHA",
"destino"=>"FRANCIA",
"tren"=>"AVE",
"salida"=>"10:00",
"llegada"=>"13:25"),
array("origen"=>"FRANCIA",
"destino"=>"ATOCHA",
"tren"=>"AVE",
"salida"=>"11:00",
"llegada"=>"14:25"),
array("origen"=>"FRANCIA",
"destino"=>"ATOCHA",
"tren"=>"AVE",
"salida"=>"13:00",
"llegada"=>"15:25"),
array("origen"=>"SANTA JUSTA",
"destino"=>"CAZALLA-CONSTANTINA",
"tren"=>"REGIONAL",
"salida"=>"09:00",
"llegada"=>"11:00"),
array("origen"=>"SANTA JUSTA",
"destino"=>"MALAGA",
"tren"=>"REGIONAL",
"salida"=>"16:00",
"llegada"=>"17:24"),

array("origen"=>"MALAGA",
"destino"=>"SANTA JUSTA",
"tren"=>"REGIONAL",
"salida"=>"18:00",
"llegada"=>"19:44")
);
echo "<pre>";
print_r($trayectos);
echo "</pre>";
?>